# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d95917266e44ab931dd8f9eb1bdd12bc1fd173d715d1adbc9c6f15b2c1cf6ff6ea6955dfc0514d3035781a07fc2fa3a3f9e16df046fd3354b2772b9fa6a575b6

test:
  secret_key_base: b3fe5bc59aefd50a1bd85ed702320ac2ddc075d94e7049d2e625c6b3cadc1db6abb851452a90f0324f0363f3033fe8e1ca26c17834d0934f37c1bcd1cbf119dc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
